# https://blog.travis-ci.com/2018-10-11-windows-early-release
# https://docs.travis-ci.com/user/reference/windows
# https://chocolatey.org/packages/python
# https://www.pyinstaller.org
# https://travis-ci.community/t/pyinstaller-can-build-and-run-a-windows-exe-but-no-console-output-is-visible/2767
os: windows      # Windows Server, version 1803
language: shell  # 'language: python' is not yet supported on Windows

env:
  global:
    - PY37PATH=/c/Python37:/c/Python37/Scripts
  
matrix:
  include:
    - name: "Py3: Run tests"
      env: PATH=$PY37PATH:$PATH
      before_install:
        - choco install python

install:
  - python -m pip install --upgrade pip
  #- pip install -r requirements.txt
  - pip install pyinstaller
  - pip install requests 
  - pip install beautifulsoup4

script:
  - pyinstaller --onefile sat.py
  - sleep 1  # Allow pyinstaller to finish writing to stdout
  - ls -l dist
  - dist/sat.exe -h
  - echo "Did something print?!?"
